import type { Dispatch, SetStateAction } from "react"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../ui/select"

type Props = {
  location: string
  setLocation: Dispatch<SetStateAction<string>>
}

export default function LocationDropdown({ location, setLocation }: Readonly<Props>) {
  return (
    <Select value={location} onValueChange={setLocation}>
  <SelectTrigger className="w-full xs:w-[280px]">
    <SelectValue placeholder="Select a capital" />
  </SelectTrigger>
  <SelectContent className="z-1001 max-h-80 overflow-y-auto">
    {locations.map(({ flag, country, capital }) => (
      <SelectItem key={capital} value={capital}>
        {flag} {capital} — {country}
      </SelectItem>
    ))}
  </SelectContent>
</Select>

  )
}

const locations = [
  { flag: "🇦🇫", country: "Afghanistan", capital: "Kabul" },
  { flag: "🇦🇱", country: "Albania", capital: "Tirana" },
  { flag: "🇩🇿", country: "Algeria", capital: "Algiers" },
  { flag: "🇦🇩", country: "Andorra", capital: "Andorra la Vella" },
  { flag: "🇦🇴", country: "Angola", capital: "Luanda" },
  { flag: "🇦🇬", country: "Antigua and Barbuda", capital: "Saint John's" },
  { flag: "🇦🇷", country: "Argentina", capital: "Buenos Aires" },
  { flag: "🇦🇲", country: "Armenia", capital: "Yerevan" },
  { flag: "🇦🇺", country: "Australia", capital: "Canberra" },
  { flag: "🇦🇹", country: "Austria", capital: "Vienna" },
  { flag: "🇦🇿", country: "Azerbaijan", capital: "Baku" },
  { flag: "🇧🇸", country: "Bahamas", capital: "Nassau" },
  { flag: "🇧🇭", country: "Bahrain", capital: "Manama" },
  { flag: "🇧🇩", country: "Bangladesh", capital: "Dhaka" },
  { flag: "🇧🇧", country: "Barbados", capital: "Bridgetown" },
  { flag: "🇧🇾", country: "Belarus", capital: "Minsk" },
  { flag: "🇧🇪", country: "Belgium", capital: "Brussels" },
  { flag: "🇧🇿", country: "Belize", capital: "Belmopan" },
  { flag: "🇧🇯", country: "Benin", capital: "Porto-Novo" },
  { flag: "🇧🇹", country: "Bhutan", capital: "Thimphu" },
  { flag: "🇧🇴", country: "Bolivia", capital: "La Paz" },
  { flag: "🇧🇦", country: "Bosnia and Herzegovina", capital: "Sarajevo" },
  { flag: "🇧🇼", country: "Botswana", capital: "Gaborone" },
  { flag: "🇧🇷", country: "Brazil", capital: "Brasília" },
  { flag: "🇧🇳", country: "Brunei", capital: "Bandar Seri Begawan" },
  { flag: "🇧🇬", country: "Bulgaria", capital: "Sofia" },
  { flag: "🇧🇫", country: "Burkina Faso", capital: "Ouagadougou" },
  { flag: "🇧🇮", country: "Burundi", capital: "Gitega" },
  { flag: "🇨🇻", country: "Cabo Verde", capital: "Praia" },
  { flag: "🇰🇭", country: "Cambodia", capital: "Phnom Penh" },
  { flag: "🇨🇲", country: "Cameroon", capital: "Yaoundé" },
  { flag: "🇨🇦", country: "Canada", capital: "Ottawa" },
  { flag: "🇨🇫", country: "Central African Republic", capital: "Bangui" },
  { flag: "🇹🇩", country: "Chad", capital: "N'Djamena" },
  { flag: "🇨🇱", country: "Chile", capital: "Santiago" },
  { flag: "🇨🇳", country: "China", capital: "Beijing" },
  { flag: "🇨🇴", country: "Colombia", capital: "Bogotá" },
  { flag: "🇰🇲", country: "Comoros", capital: "Moroni" },
  { flag: "🇨🇬", country: "Congo", capital: "Brazzaville" },
  { flag: "🇨🇩", country: "Democratic Republic of the Congo", capital: "Kinshasa" },
  { flag: "🇨🇷", country: "Costa Rica", capital: "San José" },
  { flag: "🇭🇷", country: "Croatia", capital: "Zagreb" },
  { flag: "🇨🇺", country: "Cuba", capital: "Havana" },
  { flag: "🇨🇾", country: "Cyprus", capital: "Nicosia" },
  { flag: "🇨🇿", country: "Czechia", capital: "Prague" },
  { flag: "🇩🇰", country: "Denmark", capital: "Copenhagen" },
  { flag: "🇩🇯", country: "Djibouti", capital: "Djibouti" },
  { flag: "🇩🇲", country: "Dominica", capital: "Roseau" },
  { flag: "🇩🇴", country: "Dominican Republic", capital: "Santo Domingo" },
  { flag: "🇪🇨", country: "Ecuador", capital: "Quito" },
  { flag: "🇪🇬", country: "Egypt", capital: "Cairo" },
  { flag: "🇸🇻", country: "El Salvador", capital: "San Salvador" },
  { flag: "🇬🇶", country: "Equatorial Guinea", capital: "Malabo" },
  { flag: "🇪🇷", country: "Eritrea", capital: "Asmara" },
  { flag: "🇪🇪", country: "Estonia", capital: "Tallinn" },
  { flag: "🇸🇿", country: "Eswatini", capital: "Mbabane" },
  { flag: "🇪🇹", country: "Ethiopia", capital: "Addis Ababa" },
  { flag: "🇫🇯", country: "Fiji", capital: "Suva" },
  { flag: "🇫🇮", country: "Finland", capital: "Helsinki" },
  { flag: "🇫🇷", country: "France", capital: "Paris" },
  { flag: "🇬🇦", country: "Gabon", capital: "Libreville" },
  { flag: "🇬🇲", country: "Gambia", capital: "Banjul" },
  { flag: "🇬🇪", country: "Georgia", capital: "Tbilisi" },
  { flag: "🇩🇪", country: "Germany", capital: "Berlin" },
  { flag: "🇬🇭", country: "Ghana", capital: "Accra" },
  { flag: "🇬🇷", country: "Greece", capital: "Athens" },
  { flag: "🇬🇩", country: "Grenada", capital: "Saint George’s" },
  { flag: "🇬🇹", country: "Guatemala", capital: "Guatemala City" },
  { flag: "🇬🇳", country: "Guinea", capital: "Conakry" },
  { flag: "🇬🇼", country: "Guinea-Bissau", capital: "Bissau" },
  { flag: "🇬🇾", country: "Guyana", capital: "Georgetown" },
  { flag: "🇭🇹", country: "Haiti", capital: "Port-au-Prince" },
  { flag: "🇭🇳", country: "Honduras", capital: "Tegucigalpa" },
  { flag: "🇭🇺", country: "Hungary", capital: "Budapest" },
  { flag: "🇮🇸", country: "Iceland", capital: "Reykjavík" },
  { flag: "🇮🇳", country: "India", capital: "New Delhi" },
  { flag: "🇮🇩", country: "Indonesia", capital: "Jakarta" },
  { flag: "🇮🇷", country: "Iran", capital: "Tehran" },
  { flag: "🇮🇶", country: "Iraq", capital: "Baghdad" },
  { flag: "🇮🇪", country: "Ireland", capital: "Dublin" },
  { flag: "🇮🇱", country: "Israel", capital: "Jerusalem" },
  { flag: "🇮🇹", country: "Italy", capital: "Rome" },
  { flag: "🇯🇲", country: "Jamaica", capital: "Kingston" },
  { flag: "🇯🇵", country: "Japan", capital: "Tokyo" },
  { flag: "🇯🇴", country: "Jordan", capital: "Amman" },
  { flag: "🇰🇿", country: "Kazakhstan", capital: "Astana" },
  { flag: "🇰🇪", country: "Kenya", capital: "Nairobi" },
  { flag: "🇰🇮", country: "Kiribati", capital: "Tarawa" },
  { flag: "🇰🇼", country: "Kuwait", capital: "Kuwait City" },
  { flag: "🇰🇬", country: "Kyrgyzstan", capital: "Bishkek" },
  { flag: "🇱🇦", country: "Laos", capital: "Vientiane" },
  { flag: "🇱🇻", country: "Latvia", capital: "Riga" },
  { flag: "🇱🇧", country: "Lebanon", capital: "Beirut" },
  { flag: "🇱🇸", country: "Lesotho", capital: "Maseru" },
  { flag: "🇱🇷", country: "Liberia", capital: "Monrovia" },
  { flag: "🇱🇾", country: "Libya", capital: "Tripoli" },
  { flag: "🇱🇮", country: "Liechtenstein", capital: "Vaduz" },
  { flag: "🇱🇹", country: "Lithuania", capital: "Vilnius" },
  { flag: "🇱🇺", country: "Luxembourg", capital: "Luxembourg City" },
  { flag: "🇲🇬", country: "Madagascar", capital: "Antananarivo" },
  { flag: "🇲🇼", country: "Malawi", capital: "Lilongwe" },
  { flag: "🇲🇾", country: "Malaysia", capital: "Kuala Lumpur" },
  { flag: "🇲🇻", country: "Maldives", capital: "Malé" },
  { flag: "🇲🇱", country: "Mali", capital: "Bamako" },
  { flag: "🇲🇹", country: "Malta", capital: "Valletta" },
  { flag: "🇲🇭", country: "Marshall Islands", capital: "Majuro" },
  { flag: "🇲🇷", country: "Mauritania", capital: "Nouakchott" },
  { flag: "🇲🇺", country: "Mauritius", capital: "Port Louis" },
  { flag: "🇲🇽", country: "Mexico", capital: "Mexico City" },
  { flag: "🇫🇲", country: "Micronesia", capital: "Palikir" },
  { flag: "🇲🇩", country: "Moldova", capital: "Chișinău" },
  { flag: "🇲🇨", country: "Monaco", capital: "Monaco" },
  { flag: "🇲🇳", country: "Mongolia", capital: "Ulaanbaatar" },
  { flag: "🇲🇪", country: "Montenegro", capital: "Podgorica" },
  { flag: "🇲🇦", country: "Morocco", capital: "Rabat" },
  { flag: "🇲🇿", country: "Mozambique", capital: "Maputo" },
  { flag: "🇲🇲", country: "Myanmar", capital: "Naypyidaw" },
  { flag: "🇳🇦", country: "Namibia", capital: "Windhoek" },
  { flag: "🇳🇷", country: "Nauru", capital: "Yaren" },
  { flag: "🇳🇵", country: "Nepal", capital: "Kathmandu" },
  { flag: "🇳🇱", country: "Netherlands", capital: "Amsterdam" },
  { flag: "🇳🇿", country: "New Zealand", capital: "Wellington" },
  { flag: "🇳🇮", country: "Nicaragua", capital: "Managua" },
  { flag: "🇳🇪", country: "Niger", capital: "Niamey" },
  { flag: "🇳🇬", country: "Nigeria", capital: "Abuja" },
  { flag: "🇰🇵", country: "North Korea", capital: "Pyongyang" },
  { flag: "🇲🇰", country: "North Macedonia", capital: "Skopje" },
  { flag: "🇳🇴", country: "Norway", capital: "Oslo" },
  { flag: "🇴🇲", country: "Oman", capital: "Muscat" },
  { flag: "🇵🇰", country: "Pakistan", capital: "Islamabad" },
  { flag: "🇵🇼", country: "Palau", capital: "Ngerulmud" },
  { flag: "🇵🇸", country: "Palestine", capital: "Ramallah" },
  { flag: "🇵🇦", country: "Panama", capital: "Panama City" },
  { flag: "🇵🇬", country: "Papua New Guinea", capital: "Port Moresby" },
  { flag: "🇵🇾", country: "Paraguay", capital: "Asunción" },
  { flag: "🇵🇪", country: "Peru", capital: "Lima" },
  { flag: "🇵🇭", country: "Philippines", capital: "Manila" },
  { flag: "🇵🇱", country: "Poland", capital: "Warsaw" },
  { flag: "🇵🇹", country: "Portugal", capital: "Lisbon" },
  { flag: "🇶🇦", country: "Qatar", capital: "Doha" },
  { flag: "🇷🇴", country: "Romania", capital: "Bucharest" },
  { flag: "🇷🇺", country: "Russia", capital: "Moscow" },
  { flag: "🇷🇼", country: "Rwanda", capital: "Kigali" },
  { flag: "🇰🇳", country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { flag: "🇱🇨", country: "Saint Lucia", capital: "Castries" },
  { flag: "🇻🇨", country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { flag: "🇼🇸", country: "Samoa", capital: "Apia" },
  { flag: "🇸🇲", country: "San Marino", capital: "San Marino" },
  { flag: "🇸🇹", country: "Sao Tome and Principe", capital: "São Tomé" },
  { flag: "🇸🇦", country: "Saudi Arabia", capital: "Riyadh" },
  { flag: "🇸🇳", country: "Senegal", capital: "Dakar" },
  { flag: "🇷🇸", country: "Serbia", capital: "Belgrade" },
  { flag: "🇸🇨", country: "Seychelles", capital: "Victoria" },
  { flag: "🇸🇱", country: "Sierra Leone", capital: "Freetown" },
  { flag: "🇸🇬", country: "Singapore", capital: "Singapore" },
  { flag: "🇸🇰", country: "Slovakia", capital: "Bratislava" },
  { flag: "🇸🇮", country: "Slovenia", capital: "Ljubljana" },
  { flag: "🇸🇧", country: "Solomon Islands", capital: "Honiara" },
  { flag: "🇸🇴", country: "Somalia", capital: "Mogadishu" },
  { flag: "🇿🇦", country: "South Africa", capital: "Pretoria" },
  { flag: "🇰🇷", country: "South Korea", capital: "Seoul" },
  { flag: "🇸🇸", country: "South Sudan", capital: "Juba" },
  { flag: "🇪🇸", country: "Spain", capital: "Madrid" },
  { flag: "🇱🇰", country: "Sri Lanka", capital: "Colombo" },
  { flag: "🇸🇩", country: "Sudan", capital: "Khartoum" },
  { flag: "🇸🇷", country: "Suriname", capital: "Paramaribo" },
  { flag: "🇸🇪", country: "Sweden", capital: "Stockholm" },
  { flag: "🇨🇭", country: "Switzerland", capital: "Bern" },
  { flag: "🇸🇾", country: "Syria", capital: "Damascus" },
  { flag: "🇹🇼", country: "Taiwan", capital: "Taipei" },
  { flag: "🇹🇯", country: "Tajikistan", capital: "Dushanbe" },
  { flag: "🇹🇿", country: "Tanzania", capital: "Dodoma" },
  { flag: "🇹🇭", country: "Thailand", capital: "Bangkok" },
  { flag: "🇹🇱", country: "Timor-Leste", capital: "Dili" },
  { flag: "🇹🇬", country: "Togo", capital: "Lomé" },
  { flag: "🇹🇴", country: "Tonga", capital: "Nukuʻalofa" },
  { flag: "🇹🇹", country: "Trinidad and Tobago", capital: "Port of Spain" },
  { flag: "🇹🇳", country: "Tunisia", capital: "Tunis" },
  { flag: "🇹🇷", country: "Turkey", capital: "Ankara" },
  { flag: "🇹🇲", country: "Turkmenistan", capital: "Ashgabat" },
  { flag: "🇹🇻", country: "Tuvalu", capital: "Funafuti" },
  { flag: "🇺🇬", country: "Uganda", capital: "Kampala" },
  { flag: "🇺🇦", country: "Ukraine", capital: "Kyiv" },
  { flag: "🇦🇪", country: "United Arab Emirates", capital: "Abu Dhabi" },
  { flag: "🇬🇧", country: "United Kingdom", capital: "London" },
  { flag: "🇺🇸", country: "United States", capital: "Washington, D.C." },
  { flag: "🇺🇾", country: "Uruguay", capital: "Montevideo" },
  { flag: "🇺🇿", country: "Uzbekistan", capital: "Tashkent" },
  { flag: "🇻🇺", country: "Vanuatu", capital: "Port Vila" },
  { flag: "🇻🇦", country: "Vatican City", capital: "Vatican City" },
  { flag: "🇻🇪", country: "Venezuela", capital: "Caracas" },
  { flag: "🇻🇳", country: "Vietnam", capital: "Hanoi" },
  { flag: "🇾🇪", country: "Yemen", capital: "Sana’a" },
  { flag: "🇿🇲", country: "Zambia", capital: "Lusaka" },
  { flag: "🇿🇼", country: "Zimbabwe", capital: "Harare" }
];

